---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
  namespace: testing
data:
  config.yaml: |
    ---
    devicesPort: 50051
    gatewayPort: 8080
    debug: true # in dev


